name: Github Actions Excercise
on: push
jobs:
    install:
        runs-on: ubuntu-latest
        steps: 
            - name : Get code
              uses : actions/checkout@v4.1.0
            - name : Install NodeJs
              uses : actions/setup-node@v3
              with :
                node-version : 20.3.1
            - name : Install dependencies
              run : npm ci # same with npm install but it locks the version 
            - name : Run tests
              run : npm test
    eject:
        needs: install
        runs-on: ubuntu-latest
        steps: 
            - name : Get code
              uses : actions/checkout@v4.1.0
            - name : Install NodeJs
              uses : actions/setup-node@v3
              with :
                node-version : 20.3.1
            - name : Install dependencies
              run : npm ci # same with npm install but it locks the version 
            - name : Run eject
              run: npm eject
    deploy: 
        needs: eject # Run jobs after each other, also if want to run more than one add the array []
        runs-on: ubuntu-latest
        steps:
            - name : Get code
            # check the repository we are using this code                    
              uses : actions/checkout@v4.1.0
            - name : Install NodeJs
              uses : actions/setup-node@v3
              with :
                node-version : 20.3.1
            - name : Install dependencies
              run : npm ci # same with npm install but it locks the version 
            - name : Build Project
              run : npm run build
            - name : Deploy
              run : echo "Deploying..."